---
extends: default

rules:
  document-start: disable
  line-length:
    max: 200
    level: warning
  comments:
    min-spaces-from-content: 1
  trailing-spaces:
    level: warning

ignore: |
  node_modules/
  .git/
  dist/
  build/
