---
extends: default

rules:
  document-start: disable
  line-length:
    max: 200
    level: warning
  comments:
    min-spaces-from-content: 1
  trailing-spaces:
    level: warning
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
    level: warning
  truthy:
    # Allow 'on' keyword in GitHub Actions workflows
    allowed-values: ['true', 'false', 'on']
    check-keys: false

ignore: |
  node_modules/
  .git/
  dist/
  build/
  pnpm-lock.yaml
  package-lock.json
  yarn.lock
