name: 'Capture Job Output'
description: 'Captures job summary and logs for CrewAI analysis'
inputs:
  job-name:
    description: 'Name of the job (used for folder structure)'
    required: true
  job-conclusion:
    description: 'Job conclusion (success, failure, cancelled)'
    required: true
    default: 'success'

runs:
  using: 'composite'
  steps:
    - name: Capture job summary and logs
      shell: bash
      run: |
        set -e

        JOB_NAME="${{ inputs.job-name }}"
        JOB_FOLDER=$(echo "$JOB_NAME" | tr '[:upper:]' '[:lower:]' | tr ' /' '-')
        OUTPUT_DIR="$GITHUB_WORKSPACE/.crewai-job-output/$JOB_FOLDER"

        echo "::group::Capturing output for job: $JOB_NAME"
        mkdir -p "$OUTPUT_DIR"

        # 1. Copy job summary - check multiple sources
        FOUND_SUMMARY="false"

        # First, check for explicit summary file (preferred - set by workflow)
        EXPLICIT_SUMMARY="$GITHUB_WORKSPACE/.crewai-job-output/current-job-summary.md"
        if [ -f "$EXPLICIT_SUMMARY" ] && [ -s "$EXPLICIT_SUMMARY" ]; then
          mv "$EXPLICIT_SUMMARY" "$OUTPUT_DIR/summary.md"
          SUMMARY_LINES=$(wc -l < "$OUTPUT_DIR/summary.md" | tr -d ' ')
          SUMMARY_BYTES=$(wc -c < "$OUTPUT_DIR/summary.md" | tr -d ' ')
          echo "  Copied explicit summary ($SUMMARY_LINES lines, $SUMMARY_BYTES bytes)"
          FOUND_SUMMARY="true"
        fi

        # Second, try GITHUB_STEP_SUMMARY (may not work in composite actions)
        if [ "$FOUND_SUMMARY" = "false" ] && [ -n "$GITHUB_STEP_SUMMARY" ] && [ -f "$GITHUB_STEP_SUMMARY" ] && [ -s "$GITHUB_STEP_SUMMARY" ]; then
          cp "$GITHUB_STEP_SUMMARY" "$OUTPUT_DIR/summary.md"
          SUMMARY_LINES=$(wc -l < "$OUTPUT_DIR/summary.md" | tr -d ' ')
          SUMMARY_BYTES=$(wc -c < "$OUTPUT_DIR/summary.md" | tr -d ' ')
          echo "  Copied GITHUB_STEP_SUMMARY ($SUMMARY_LINES lines, $SUMMARY_BYTES bytes)"
          FOUND_SUMMARY="true"
        fi

        # Fallback: create placeholder
        if [ "$FOUND_SUMMARY" = "false" ]; then
          echo "# Job: $JOB_NAME" > "$OUTPUT_DIR/summary.md"
          echo "" >> "$OUTPUT_DIR/summary.md"
          echo "Step summary not captured. Check workflow configuration." >> "$OUTPUT_DIR/summary.md"
          echo "  No summary found - created placeholder"
        fi

        # 2. Copy captured log (if exists - jobs redirect to this)
        if [ -f "$GITHUB_WORKSPACE/.crewai-job-output/current-job.log" ]; then
          mv "$GITHUB_WORKSPACE/.crewai-job-output/current-job.log" "$OUTPUT_DIR/log.txt"
          LOG_SIZE=$(wc -c < "$OUTPUT_DIR/log.txt" | tr -d ' ')
          echo "  Captured log ($LOG_SIZE bytes)"
        else
          echo "[Log not captured - check job configuration]" > "$OUTPUT_DIR/log.txt"
          echo "  No log file found - created placeholder"
        fi

        # 3. Get file sizes for metadata
        LOG_SIZE_BYTES=$(stat -c%s "$OUTPUT_DIR/log.txt" 2>/dev/null || stat -f%z "$OUTPUT_DIR/log.txt" 2>/dev/null || echo "0")
        SUMMARY_SIZE_BYTES=$(stat -c%s "$OUTPUT_DIR/summary.md" 2>/dev/null || stat -f%z "$OUTPUT_DIR/summary.md" 2>/dev/null || echo "0")

        # Check if files have real content (not just placeholders)
        HAS_REAL_LOG="false"
        HAS_REAL_SUMMARY="false"
        if [ "$LOG_SIZE_BYTES" -gt 50 ]; then
          HAS_REAL_LOG="true"
        fi
        if [ "$SUMMARY_SIZE_BYTES" -gt 50 ]; then
          HAS_REAL_SUMMARY="true"
        fi

        # 4. Create metadata JSON
        printf '%s\n' \
          '{' \
          "  \"job_name\": \"$JOB_NAME\"," \
          "  \"job_folder\": \"$JOB_FOLDER\"," \
          "  \"conclusion\": \"${{ inputs.job-conclusion }}\"," \
          "  \"workflow\": \"${{ github.workflow }}\"," \
          "  \"run_id\": \"${{ github.run_id }}\"," \
          "  \"run_number\": \"${{ github.run_number }}\"," \
          "  \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"," \
          "  \"summary_has_content\": $HAS_REAL_SUMMARY," \
          "  \"summary_size_bytes\": $SUMMARY_SIZE_BYTES," \
          "  \"log_has_content\": $HAS_REAL_LOG," \
          "  \"log_size_bytes\": $LOG_SIZE_BYTES" \
          '}' > "$OUTPUT_DIR/metadata.json"

        echo "  Created metadata"
        echo ""
        echo "Output captured to: $OUTPUT_DIR"
        ls -lh "$OUTPUT_DIR"
        echo "::endgroup::"

    - name: Upload job output artifact
      uses: actions/upload-artifact@v4
      with:
        name: ci-job-output-${{ inputs.job-name }}
        path: ${{ github.workspace }}/.crewai-job-output/
        retention-days: 7
        if-no-files-found: warn
        include-hidden-files: true
